name: 'AppStoreConnect Upload'
inputs:
 AppFilename:
  required: true
  type: string
  description: "Artifact filename ios.ipa or mac.app"
 Upload:
  required: true
  description: "Actually upload, if false, will just verify package"
 SignApp: # re-sign application with certificate and inject entitlements. This is for macos at the moment, but will probably expand to be ios compatible too
  required: true
  type: boolean
 SignPackage:
  required: true
  type: boolean
 TeamIdentifier:
  required: true
  type: string
  description: "ABCDEF09 Apple team ID for inserting into Entitlements (found in AppStore connect or signing certificates in keychain)"
 TestFlightPlatform:
  required: true
  type: string # can't have choices here
  #type: choice
  # options:
  #  - "macos"
  #  - "ios"
  #  - "tvos"
 BundleVersion:
  required: false
  type: number
  description: "Update CFBundleId (build version of app version) in Info.Plist to allow a new version to upload"

secrets:
 AppStoreConnect_Auth_Key:
   required: true
 AppStoreConnect_Auth_P8_Base64:
   required: true
 AppStoreConnect_Auth_Issuer:
   required: true
 # data for signing app
 SigningCertificate_Base64:
   required: false
 SigningCertificate_Password:
   required: false
 ProvisioningProfile_Base64:
   required: false

runs:
  using: 'node20'
  # gr: hack to fail if not running on a mac (with xcode tools)
  pre: 'This action must run on macos runners'
  pre-if: runner.os != 'macos'
  main: 'AppleAppStoreUpload.js'
